from django.core.management.base import BaseCommand
from store.models import Product, Review

class Command(BaseCommand):
    help = 'Seed database with men\'s streetwear products and reviews'

    def handle(self, *args, **kwargs):
        Product.objects.all().delete()
        Review.objects.all().delete()

        products = [
            {'name':'Shadow Oversized Tee','slug':'shadow-oversized-tee','price':89,'old_price':120,'category':'streetwear','badge':'Best Seller','rating':4.8,'reviews_count':124,'sizes':'S,M,L,XL,XXL','colors':'#000,#1a1a2e,#2d2d2d','image':'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=750&fit=crop','image_hover':'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&h=750&fit=crop','description':'Premium heavyweight 300gsm organic cotton oversized tee with dropped shoulders, ribbed crew neck, and a relaxed boxy silhouette. Double-stitched seams and pre-shrunk fabric ensure lasting quality. The perfect foundation piece for any streetwear outfit.'},
            {'name':'Noir Cargo Pants','slug':'noir-cargo-pants','price':149,'old_price':None,'category':'streetwear','badge':'New','rating':4.7,'reviews_count':89,'sizes':'S,M,L,XL','colors':'#000,#556B2F,#2d2d2d','image':'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&h=750&fit=crop','image_hover':'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&h=750&fit=crop','description':'Technical cargo pants with articulated knees, 6 utility pockets with YKK zippers, and adjustable ankle cuffs with snap buttons. Water-resistant ripstop nylon shell with brushed interior. Built for the streets.'},
            {'name':'AKVRIX Classic Hoodie','slug':'akvrix-classic-hoodie','price':129,'old_price':169,'category':'essentials','badge':'Best Seller','rating':4.9,'reviews_count':256,'sizes':'S,M,L,XL,XXL','colors':'#000,#1a1a2e,#00D4FF','image':'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&h=750&fit=crop','image_hover':'https://images.unsplash.com/photo-1578768079470-c7e3dde8f003?w=600&h=750&fit=crop','description':'Signature 400gsm heavyweight hoodie with embroidered AKVRIX logo on chest and back, kangaroo pocket, ribbed cuffs, and premium brushed fleece lining. Reinforced shoulder seams. The hoodie that started it all.'},
            {'name':'Street Bomber Jacket','slug':'street-bomber-jacket','price':249,'old_price':320,'category':'outerwear','badge':'Best Seller','rating':4.9,'reviews_count':167,'sizes':'S,M,L,XL','colors':'#000,#0d1b2a,#1a1a2e','image':'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=750&fit=crop','image_hover':'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&h=750&fit=crop','description':'Premium MA-1 inspired satin bomber with dual-zip closure, ribbed collar/cuffs/hem, quilted satin lining, and interior chest pocket. Water-resistant outer shell with custom AKVRIX branded zipper pulls. The ultimate outerwear statement.'},
            {'name':'Onyx Track Set','slug':'onyx-track-set','price':189,'old_price':None,'category':'streetwear','badge':'Best Seller','rating':4.8,'reviews_count':142,'sizes':'S,M,L,XL','colors':'#000,#1a1a2e,#00D4FF','image':'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&h=750&fit=crop','image_hover':'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=600&h=750&fit=crop','description':'Full tracksuit set with tapered joggers, zip-up jacket, contrast piping, and embroidered branding. Moisture-wicking tech fabric with 4-way stretch. Zippered side pockets on both pieces.'},
            {'name':'Minimal Logo Tee','slug':'minimal-logo-tee','price':59,'old_price':None,'category':'essentials','badge':'New','rating':4.4,'reviews_count':45,'sizes':'S,M,L,XL,XXL','colors':'#FFF,#000,#00D4FF','image':'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=600&h=750&fit=crop','image_hover':'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=600&h=750&fit=crop','description':'Clean minimal tee with subtle chest logo print in tonal or contrast colorways. 180gsm combed Ring-Spun cotton for a soft, premium hand-feel. Pre-washed for zero shrinkage.'},
            {'name':'Gold Edition Hoodie','slug':'gold-edition-hoodie','price':299,'old_price':None,'category':'limited','badge':'Limited','rating':5.0,'reviews_count':31,'sizes':'S,M,L','colors':'#000','image':'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&h=750&fit=crop','image_hover':'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=600&h=750&fit=crop','description':'Limited edition hoodie with metallic gold 3D embroidery, 500gsm ultra-heavyweight cotton, custom gold tip drawstrings, and numbered holographic tag. Only 200 pieces made worldwide. Certificate of authenticity included.'},
            {'name':'Stealth Joggers','slug':'stealth-joggers','price':109,'old_price':139,'category':'essentials','badge':'','rating':4.6,'reviews_count':67,'sizes':'S,M,L,XL','colors':'#000,#2d2d2d,#556B2F','image':'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600&h=750&fit=crop','image_hover':'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=600&h=750&fit=crop','description':'Tapered slim joggers with zippered side pockets, elastic waistband with internal drawcord, and ribbed ankle cuffs. Technical stretch twill fabric with DWR moisture-wicking coating. Laser-cut ventilation panels.'},
            {'name':'Luxe Puffer Vest','slug':'luxe-puffer-vest','price':219,'old_price':280,'category':'outerwear','badge':'Limited','rating':4.8,'reviews_count':88,'sizes':'S,M,L,XL','colors':'#000,#00D4FF','image':'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=600&h=750&fit=crop','image_hover':'https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?w=600&h=750&fit=crop','description':'Premium 700-fill goose down puffer vest with matte ripstop shell, stand collar, hidden YKK zip with storm flap, and internal zippered pocket. Packable and lightweight at just 310g. Reflective AKVRIX logo on back.'},
            {'name':'Tech Windbreaker','slug':'tech-windbreaker','price':179,'old_price':None,'category':'outerwear','badge':'New','rating':4.5,'reviews_count':52,'sizes':'S,M,L,XL','colors':'#000,#0d1b2a,#00D4FF','image':'https://images.unsplash.com/photo-1548126032-079a0fb0099d?w=600&h=750&fit=crop','image_hover':'https://images.unsplash.com/photo-1495385794356-15371f348c31?w=600&h=750&fit=crop','description':'Ultralight 3-layer windbreaker with sealed seams, adjustable hood with cord locks, half-zip with chin guard, and packable design. Reflective detailing for visibility. Breathable waterproof membrane rated 10,000mm.'},
            {'name':'Raw Denim Jacket','slug':'raw-denim-jacket','price':199,'old_price':259,'category':'outerwear','badge':'','rating':4.7,'reviews_count':93,'sizes':'S,M,L,XL','colors':'#000,#191970','image':'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=750&fit=crop','image_hover':'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&h=750&fit=crop','description':'Heavyweight 14oz raw selvedge denim jacket with copper hardware, hand-distressed detailing, and sherpa-lined collar. Custom AKVRIX rivets and branded leather patch. Will develop unique fading patterns with wear.'},
            {'name':'Essential Crewneck','slug':'essential-crewneck','price':79,'old_price':None,'category':'essentials','badge':'','rating':4.6,'reviews_count':112,'sizes':'S,M,L,XL,XXL','colors':'#000,#1a1a2e,#FFF','image':'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=600&h=750&fit=crop','image_hover':'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&h=750&fit=crop','description':'Premium 350gsm cotton-poly blend crewneck sweatshirt with brushed fleece interior, ribbed trims, and embossed tonal logo. Relaxed fit with dropped shoulders. The everyday essential elevated.'},
            {'name':'Phantom Shorts','slug':'phantom-shorts','price':69,'old_price':89,'category':'streetwear','badge':'','rating':4.3,'reviews_count':38,'sizes':'S,M,L,XL','colors':'#000,#2d2d2d','image':'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=600&h=750&fit=crop','image_hover':'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600&h=750&fit=crop','description':'Relaxed mesh-lined shorts with 7-inch inseam, zippered cargo pockets, elastic waistband with drawcord, and tonal logo embroidery. Quick-dry fabric with UV50+ protection. Perfect for summer streetwear.'},
            {'name':'Cyber Hoodie','slug':'cyber-hoodie','price':159,'old_price':None,'category':'new','badge':'New','rating':4.7,'reviews_count':29,'sizes':'S,M,L,XL','colors':'#000,#00D4FF','image':'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&h=750&fit=crop','image_hover':'https://images.unsplash.com/photo-1578768079470-c7e3dde8f003?w=600&h=750&fit=crop','description':'Futuristic hoodie with reflective cyberpunk-inspired graphic prints, hidden thumb-hole cuffs, side-zip detailing, and glow-in-the-dark AKVRIX branding. 400gsm heavyweight cotton with tech-weave panels.'},
            {'name':'Founder\'s Collection Jacket','slug':'founders-collection-jacket','price':399,'old_price':None,'category':'limited','badge':'Limited','rating':5.0,'reviews_count':15,'sizes':'S,M,L','colors':'#000','image':'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=750&fit=crop','image_hover':'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&h=750&fit=crop','description':'Ultra-premium leather and nylon hybrid jacket from the Founder\'s Collection. Hand-numbered with brass plate, Japanese YKK Excella zippers, Alcantara-lined pockets, and packaging in custom wooden box. Only 50 pieces exist.'},
            {'name':'Apex Performance Tee','slug':'apex-performance-tee','price':69,'old_price':None,'category':'new','badge':'New','rating':4.5,'reviews_count':41,'sizes':'S,M,L,XL,XXL','colors':'#000,#FFF,#00D4FF','image':'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=750&fit=crop','image_hover':'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&h=750&fit=crop','description':'Technical performance tee with moisture-wicking Dri-Fit fabric, mesh ventilation panels, flatlock seams, and reflective AKVRIX logo. 4-way stretch for full range of motion. From gym to street seamlessly.'},
        ]

        for pd in products:
            Product.objects.create(**pd)

        # Add reviews to all products
        review_data = [
            {'name':'Rahul M.','rating':5,'text':'Absolutely insane quality. The fabric feels premium and the fit is perfect. AKVRIX is the real deal. Ordered 3 more pieces after this.'},
            {'name':'Alex K.','rating':5,'text':'Best streetwear brand I\'ve found. The attention to detail is next level — from the stitching to the packaging. Worth every rupee.'},
            {'name':'Dev S.','rating':4,'text':'Great quality, runs slightly oversized which I love. Shipping was fast. The only brand I trust for daily wear now.'},
            {'name':'Arjun P.','rating':5,'text':'The construction quality is unmatched at this price point. Heavy cotton, clean lines, no cheap shortcuts. This is what premium should feel like.'},
            {'name':'Karthik R.','rating':5,'text':'Ordered the full set and I\'m blown away. Packaging was premium, product exceeded expectations. AKVRIX has a customer for life.'},
        ]

        for product in Product.objects.all():
            for rd in review_data[:3]:
                Review.objects.create(product=product, **rd)

        self.stdout.write(self.style.SUCCESS(f'Seeded {Product.objects.count()} products and {Review.objects.count()} reviews'))
